name: Deploy Instance

on:
  workflow_dispatch:
    inputs:
      company_id:
        description: 'Choice of company to deploy'
        required: true
        default: 'birdseye'
        type: choice
        options:
          - birdseye
          - cablebusters
          - ne_support
          - eztv_support

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Load Config and Build
        run: npm run build
        env:
          INSTANCE_CONFIG: ${{ github.event.inputs.company_id }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --dir=dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets[format('NETLIFY_SITE_ID_{0}', github.event.inputs.company_id)] }}
